# Generated by Django 6.0.2 on 2026-02-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('role', models.CharField(choices=[('read_only', 'Read Only'), ('contributor', 'Contributor'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='read_only', help_text='Permission level for this API key', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this key is used for')),
                ('created_by', models.CharField(blank=True, help_text='Who created this API key', max_length=100)),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this key was used', null=True)),
            ],
            options={
                'verbose_name': 'Role API Key',
                'verbose_name_plural': 'Role API Keys',
                'ordering': ['-created'],
            },
        ),
    ]
