from typing import Dict, List

LEVEL_PRIORITIES: Dict[str, List[str]] = {
    "thps1": [
        "Warehouse",
        "School",
        "Mall",
        "Chicago (Competition 1)",
        "Downtown",
        "Downhill Jam",
        "Burnside (Competition 2)",
        "San Francisco",
        "Roswell (Competition 3)",
    ],
    "thps2": [
        "Hangar",
        "School II",
        "Marseille (Competition 1)",
        "NY City",
        "Venice",
        "Skatestreet (Competition 2)",
        "Philadelphia",
        "Bullring (Competition 3)",
    ],
    "thps3": [
        "Foundry",
        "Canada",
        "Rio (Competition 1)",
        "Suburbia",
        "Airport",
        "Skater Island (Competition 2)",
        "Los Angeles",
        "Tokyo (Competition 3)",
        "Cruise Ship",
    ],
    "thps4": [
        "Alcatraz - Bams Pro Specific Challenge",
        "Alcatraz - Collect the S-K-A-T-E letters",
        "Alcatraz - Distract the Guards",
        "Alcatraz - Dunk 30 Tourists",
        "Alcatraz - Elissas Pro Specific Challenge",
        "Alcatraz - Escape from Alcatraz",
        "Alcatraz - Find the Guards Keys",
        "Alcatraz - Nail the Mega-Combos they yell out",
        "Alcatraz - Pose for 6 Pictures",
        "Alcatraz - Pull off Mullens Tech Trick",
        "Alcatraz - Revert Madness",
        "Alcatraz - Runes Pro Specific Challenge",
        "Alcatraz - Semi Flip the Bulldozer",
        "Alcatraz - Take the Alcatraz Tour",
        "Carnival - Collect 10 ride tickets",
        "Carnival - Collect 6 souvenir photos",
        "Carnival - Do a 500000 point combo",
        "Carnival - Get a High Score 750000 points",
        "Carnival - Get a Sick Score 1500000 points",
        "Carnival - Help tear down the competition",
        "Carnival - Nail a 900 on the Rocket ride",
        "Carnival - Try not to boot",
        "Chicago - 900 off bridge to the ferrys top deck",
        "Chicago -  Do a 100000 point combo on the ledge",
        "Chicago - Get a High Score 900000 points",
        "Chicago - Get a Sick Score 1500000 points",
        "Chicago - Grind 5 Fire Hydrants",
        "Chicago - Put Bugs on 5 Mafiosos",
        "College -  Collect the S-K-A-T-E letters",
        "College - Combo the Benches Stairs and Flag Pole",
        "College - Gap between floats 10 times",
        "College - Get a High Score 40000 points",
        "College - Get a Pro Score 75000 points",
        "College - Get a Sick Score 250000 points",
        "College - Get all 4 Masters Lip Gaps",
        "College - Get back at the 5 frat boys",
        "College - Grind down Officer Toms Banners",
        "College - Jamies Pro Specific Challenge",
        "College - Nail a 360 Varial McTwist",
        "College - Race the Inline Skater",
        "College - Spine Transfer over the wall",
        "College - Tonys Pro Specific Challenge",
        "College - Warn the other skaters",
        "Kona - 50k combo the bowl - No hitting bottles",
        "Kona - Collect the S-K-A-T-E letters",
        "Kona - Collect the Skate Camp waivers",
        "Kona - Find and get all 7 Channel Gaps",
        "Kona - Find the 4 Missing Rental Gear Items",
        "Kona - Ollie the Magic Bum 5x.again",
        "Kona - Save the birds on the power lines",
        "Kona - Snake Run Slalom",
        "Kona - Steves Pro Specific Challenge",
        "London - Beat Muskas best 6 Combos",
        "London - Get a High Score 75000 points",
        "London - Get a Pro Score 175000 points",
        "London - Get a Sick Score 700000 points",
        "London - Ghetto Tag the SB light line",
        "London -  Grab 5 Coppers hats",
        "London - Land a 100000 point combo",
        "London - Race the Coppers around London",
        "London - Rowleys Pro Specific Challenge",
        "London - Wallride Tag 5 buses",
        "San Francisco - Andrews Pro Specific Challenge",
        "San Francisco - Chads Pro Specific Challenge",
        "San Francisco - Collect the S-K-A-T-E letters",
        "San Francisco - Darkslide the Waterside Railing",
        "San Francisco - Feed the 4 Angry Sea Lions",
        "San Francisco - Find the Messengers 5 Missing Packages",
        "San Francisco - Get a High Score 50000 points",
        "San Francisco - Get a Pro Score 100000 points",
        "San Francisco - Get a Sick Score 300000 points",
        "San Francisco - Grind the Blockers off the Ledges",
        "San Francisco - Lip Trick the 3 Pier Signs",
        "San Francisco - Manual Gap and Manual the setup",
        "San Francisco - Race the Bike Messenger",
        "San Francisco - Race to get the Camera",
        "San Francisco - Save Painter Neal",
        "Shipyard - Buckys Pro specific challenge",
        "Shipyard - Collect the rivets",
        "Shipyard - Erics Pro Specific Challenge",
        "Shipyard - Get a High Score 65000 Points",
        "Shipyard - Get a Pro Score 150000 Points",
        "Shipyard - Get a Sick Score 600000 Points",
        "Shipyard - Heelflip FS Invert the freight container",
        "Shipyard - Slap the buoy",
        "Shipyard - Welder lunch delivery",
        "Zoo - Beat Bobs 3 best combos",
        "Zoo - Bobs Pro Specific Challenge",
        "Zoo - Catch the 5 runaway Penguins",
        "Zoo - Combo scare 40 Birds",
        "Zoo - Do a Sit Down Air over the Lions cage",
        "Zoo - Feed the Hippos",
        "Zoo - Get a High Score 80000 points",
        "Zoo - Get a Pro Score 200000 points",
        "Zoo - Get a Sick Score 800000 points",
        "Zoo - Get Kong back in his cage",
        "Zoo - Grind the 4 Zoo banners",
        "Zoo - Hardflip and Heelflip over Kenny",
        "Zoo - Help the Lion Tamer escape",
        "Zoo - Lure the Lions back to the cage",
        "Zoo - Stop the Monkey from escaping",
        "Zoo - Transfer over Elephant Rock",
    ],
    "thug1": [
        "New Jersey",
        "Manhattan",
        "Tampa",
        "San Diego",
        "Hawaii",
        "Vancouver",
        "Slam City Jam",
        "Vancouver 2",
        "Moscow",
        "New Jersey 2",
        "Pro Team Challenge",
        "Eric's Line",
    ],
    "thug2": [
        "Training",
        "Boston",
        "Barcelona",
        "Berlin",
        "Australia",
        "New Orleans",
        "Skatopia",
        "The Triangle",
        "School",
        "Philadelphia",
        "Downhill Jam",
        "Los Angeles",
        "Canada",
        "Airport",
    ],
    "thaw": [
        "Minneapolis",
        "Santa Cruz",
        "The Mall",
        "Chicago",
        "Kyoto",
        "The Ruins",
        "Atlanta",
        "Marseilles",
    ],
    "thpg": [
        "Race Around The Harbor",
        "Race Around The Slums",
        "Race Around The Love",
        "Race Around The Monuments",
        "Race Around the Museums",
        "Impress Mike",
    ],
    "thdj": [
        "San Francisco",
        "Hong Kong",
        "Edinburgh",
        "Machu Picchu",
        "Rio",
        "Rome",
        "Chicago",
        "Alps",
        "Killimanjaro",
        "Hoover Dam",
    ],
    "thps5": [
        "The Berrics",
        "Bonfire Beach",
        "School III",
        "Mega Park",
        "Rooftop",
        "The Bunker",
        "Asteroid Belt",
        "Mountain",
        "Wild West",
        "The Underground",
    ],
    "thps12": [
        "Warehouse",
        "School",
        "Mall",
        "Downtown",
        "Downhill_Jam",
        "Streets",
        "Hangar",
        "School_II",
        "NY_City",
        "Venice_Beach",
        "Philadelphia",
    ],
    "thps34": [
        "Foundry",
        "Canada",
        "Suburbia",
        "Airport",
        "Los Angeles",
        "Cruise Ship",
        "College",
        "San Francisco",
        "Alcatraz",
        "Waterpark",
        "Shipyard",
        "London",
        "Pinball",
    ],
    "thugpro": [
        "Airport",
        "Alcatraz",
        "Australia",
        "Barcelona",
        "Berlin",
        "Boston",
        "Canada",
        "Carnival",
        "Chicago",
        "College",
        "Downhill Jam",
        "Kona",
        "London",
        "Los Angeles",
        "New Orleans",
        "Philadelphia",
        "San Francisco",
        "School",
        "Shipyard",
        "Skatopia",
        "The Triangle",
        "Training",
        "Zoo",
    ],
}


def get_ordered_level_names(game_slug: str) -> List[str]:
    """Get the ordered list of level names for a game to export to Django."""
    return LEVEL_PRIORITIES.get(game_slug, [])
