# Generated by Django 4.2.1 on 2023-05-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameOverview",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="SRL Game ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                ("abbr", models.CharField(max_length=20, verbose_name="Abbreviation")),
                ("release", models.DateField(verbose_name="Release Date")),
                ("boxart", models.URLField(verbose_name="Box Art URL")),
                (
                    "defaulttime",
                    models.CharField(max_length=20, verbose_name="Default Time"),
                ),
                (
                    "platforms",
                    models.CharField(max_length=20, verbose_name="Platforms"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ILCategory",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Category ID (IL)",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Name")),
                ("url", models.URLField(verbose_name="URL")),
            ],
        ),
        migrations.CreateModel(
            name="ILRuns",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Run ID",
                    ),
                ),
                (
                    "cats",
                    models.CharField(max_length=10, verbose_name="Linked Categories"),
                ),
                ("playerid", models.CharField(max_length=10, verbose_name="Player ID")),
                ("place", models.IntegerField(verbose_name="Placing")),
                ("url", models.URLField(verbose_name="URL")),
                ("date", models.DateField(verbose_name="Submitted Date")),
                ("time", models.CharField(max_length=10, verbose_name="Time")),
                ("points", models.IntegerField(verbose_name="Packle Points")),
                ("platform", models.CharField(max_length=10, verbose_name="Platform")),
            ],
        ),
        migrations.CreateModel(
            name="Levels",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Level ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Name")),
                ("url", models.URLField(verbose_name="URL")),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Category ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Name")),
                ("url", models.URLField(verbose_name="URL")),
            ],
        ),
        migrations.CreateModel(
            name="MainRuns",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Run ID",
                    ),
                ),
                ("playerid", models.CharField(max_length=10, verbose_name="Player ID")),
                ("place", models.IntegerField(verbose_name="Placing")),
                ("url", models.URLField(verbose_name="URL")),
                ("date", models.DateField(verbose_name="Submitted Date")),
                ("time", models.CharField(max_length=10, verbose_name="Time")),
                ("points", models.IntegerField(verbose_name="Packle Points")),
                ("platform", models.CharField(max_length=10, verbose_name="Platform")),
            ],
        ),
        migrations.CreateModel(
            name="Variables",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Variable ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Name")),
                (
                    "cat",
                    models.CharField(max_length=10, verbose_name="Linked Category"),
                ),
                (
                    "scope",
                    models.CharField(max_length=12, verbose_name="Scope (FG/IL)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariableValues",
            fields=[
                ("id", models.CharField(max_length=10, verbose_name="Linked Variable")),
                (
                    "valueid",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Value ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Name")),
            ],
        ),
    ]
