# Generated by Django 5.1.1 on 2024-12-03 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variables",
            name="cat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="srl.categories",
                verbose_name="Category",
            ),
        ),
    ]
