# Generated by Django 5.2.3 on 2025-06-15 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowstreaming',
            name='streamer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='srl.players', verbose_name='Streamer'),
        ),
    ]
