# Generated by Django 4.2.1 on 2023-05-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gameoverview",
            options={"verbose_name_plural": "Game Overview"},
        ),
        migrations.RemoveField(
            model_name="ilruns",
            name="cats",
        ),
        migrations.AddField(
            model_name="ilruns",
            name="category",
            field=models.CharField(
                default="", max_length=10, verbose_name="Category ID"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ilruns",
            name="gameid",
            field=models.CharField(default="", max_length=20, verbose_name="Game ID"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ilruns",
            name="levelid",
            field=models.CharField(default="", max_length=10, verbose_name="Level ID"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mainruns",
            name="category",
            field=models.CharField(
                default="", max_length=10, verbose_name="Category ID"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mainruns",
            name="gameid",
            field=models.CharField(default="", max_length=20, verbose_name="Game ID"),
            preserve_default=False,
        ),
    ]
