# Generated by Django 5.2.11 on 2026-03-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0002_alter_nowstreaming_streamer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pronouns'),
        ),
    ]
