# Generated by Django 4.2.1 on 2023-05-11 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0002_alter_gameoverview_options_remove_ilruns_cats_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ILCategory",
        ),
    ]
