# Generated by Django 5.1.4 on 2024-12-23 23:01

import django_resized.forms
import srl.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0003_alter_variables_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awards",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                help_text="Note: Images must be at least 64px in size, must be a square (height and width must match), and the max filesize is 3MB.",
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[64, 64],
                upload_to="srl/static/srl/imgs/awards",
                validators=[srl.models.validate_image],
                verbose_name="Image",
            ),
        ),
    ]
