# Generated by Django 4.2.1 on 2023-05-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0003_delete_ilcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameoverview",
            name="platforms",
            field=models.CharField(max_length=100, verbose_name="Platforms"),
        ),
        migrations.AlterField(
            model_name="ilruns",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Submitted Date"
            ),
        ),
        migrations.AlterField(
            model_name="mainruns",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Submitted Date"
            ),
        ),
    ]
