# Generated by Django 5.1.5 on 2025-03-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0004_alter_awards_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ilruns",
            name="v_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Verified Date"
            ),
        ),
        migrations.AddField(
            model_name="mainruns",
            name="v_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Verified Date"
            ),
        ),
        migrations.AlterField(
            model_name="ilruns",
            name="date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Submitted Date"
            ),
        ),
        migrations.AlterField(
            model_name="mainruns",
            name="date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Submitted Date"
            ),
        ),
    ]
