# Generated by Django 4.2.1 on 2023-06-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0004_alter_gameoverview_platforms_alter_ilruns_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Category ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Name")),
                ("type", models.CharField(max_length=15, verbose_name="Type (IL/FG)")),
                ("url", models.URLField(verbose_name="URL")),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Players",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Player ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                ("url", models.URLField(verbose_name="URL")),
                ("pronouns", models.CharField(max_length=20, verbose_name="Pronouns")),
                ("location", models.CharField(max_length=30, verbose_name="Location")),
                ("twitch", models.CharField(max_length=20, verbose_name="Twitch")),
                ("youtube", models.CharField(max_length=20, verbose_name="YouTube")),
                ("twitter", models.CharField(max_length=20, verbose_name="Twitter")),
            ],
            options={
                "verbose_name_plural": "Players",
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Series ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Name")),
                ("url", models.URLField(verbose_name="URL")),
            ],
            options={
                "verbose_name_plural": "Series",
            },
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AlterModelOptions(
            name="ilruns",
            options={"verbose_name_plural": "IL Runs"},
        ),
        migrations.AlterModelOptions(
            name="levels",
            options={"verbose_name_plural": "Levels"},
        ),
        migrations.AlterModelOptions(
            name="mainruns",
            options={"verbose_name_plural": "Main Runs"},
        ),
        migrations.AlterModelOptions(
            name="variables",
            options={"verbose_name_plural": "Variables"},
        ),
        migrations.AlterModelOptions(
            name="variablevalues",
            options={"verbose_name_plural": "Variable Values"},
        ),
    ]
