# Generated by Django 4.2.1 on 2023-06-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0005_categories_players_series_delete_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="players",
            name="location",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="pronouns",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Pronouns"
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="twitch",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Twitch"
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="twitter",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Twitter"
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="youtube",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="YouTube"
            ),
        ),
    ]
