# Generated by Django 5.1.7 on 2025-03-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0005_ilruns_v_date_mainruns_v_date_alter_ilruns_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewRuns",
        ),
        migrations.DeleteModel(
            name="NewWRs",
        ),
        migrations.RemoveField(
            model_name="ilruns",
            name="timeframes",
        ),
        migrations.AddField(
            model_name="gameoverview",
            name="idefaulttime",
            field=models.CharField(
                choices=[
                    ("realtime", "RTA"),
                    ("realtime_noloads", "LRT"),
                    ("ingame", "IGT"),
                ],
                default="realtime",
                help_text="Sometimes leaderboards have one timing standard for full game speedruns and another standard for ILs. This setting lets you change the game-specific IL timing method. NOTE: This defaults to RTA upon a game being created and must be set manually.",
                verbose_name="ILs Default Time",
            ),
        ),
    ]
