# Generated by Django 5.1.7 on 2025-03-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0006_delete_newruns_delete_newwrs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameoverview",
            name="defaulttime",
            field=models.CharField(
                choices=[
                    ("realtime", "RTA"),
                    ("realtime_noloads", "LRT"),
                    ("ingame", "IGT"),
                ],
                default="realtime",
                verbose_name="Default Time",
            ),
        ),
        migrations.AlterField(
            model_name="gameoverview",
            name="idefaulttime",
            field=models.CharField(
                choices=[
                    ("realtime", "RTA"),
                    ("realtime_noloads", "LRT"),
                    ("ingame", "IGT"),
                ],
                default="realtime",
                help_text="Sometimes leaderboards have one timing standard for full game speedruns and another standard for ILs. This setting lets you change the game-specific IL timing method.<br />NOTE: This defaults to RTA upon a game being created and must be set manually.",
                verbose_name="ILs Default Time",
            ),
        ),
    ]
