# Generated by Django 4.2.1 on 2023-06-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0006_alter_players_location_alter_players_pronouns_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ilruns",
            name="platform",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Platform"
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="twitch",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Twitch"
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="twitter",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Twitter"
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="youtube",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="YouTube"
            ),
        ),
    ]
