# Generated by Django 5.1.7 on 2025-03-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0007_alter_gameoverview_defaulttime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameoverview",
            name="ipointsmax",
            field=models.IntegerField(
                default=100,
                help_text='Default is 100; 25 if this game contains the name "Category Extension". This is the maximum total of points an IL speedrun receives if it is the world record. All lower-ranked speedruns recieve less based upon an algorithmic formula.',
                verbose_name="IL WR Point Maximum",
            ),
        ),
        migrations.AddField(
            model_name="gameoverview",
            name="pointsmax",
            field=models.IntegerField(
                default=1000,
                help_text='Default is 1000; 25 if this game contains the name "Category Extension". This is the maximum total of points a full-game speedrun receives if it is the world record. All lower-ranked speedruns recieve less based upon an algorithmic formula.',
                verbose_name="Full Game WR Point Maximum",
            ),
        ),
    ]
