# Generated by Django 4.2.1 on 2023-06-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0007_alter_ilruns_platform_alter_players_twitch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainruns",
            name="platform",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Platform"
            ),
        ),
    ]
