# Generated by Django 4.2.1 on 2023-06-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0008_alter_mainruns_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="players",
            name="pfp",
            field=models.URLField(
                blank=True, null=True, verbose_name="Profile Picture URL"
            ),
        ),
    ]
