# Generated by Django 5.1.7 on 2025-03-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0009_alter_gameoverview_ipointsmax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainruns',
            name='timeframes',
        ),
    ]
