# Generated by Django 4.2.1 on 2023-06-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0009_players_pfp"),
    ]

    operations = [
        migrations.AddField(
            model_name="ilruns",
            name="values",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Subcategory Values"
            ),
        ),
        migrations.AddField(
            model_name="mainruns",
            name="values",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Subcategory Values"
            ),
        ),
    ]
