# Generated by Django 4.2.1 on 2023-06-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0010_ilruns_values_mainruns_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="ilruns",
            name="subcategory",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Subcategory Name"
            ),
        ),
        migrations.AddField(
            model_name="mainruns",
            name="subcategory",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Subcategory Name"
            ),
        ),
        migrations.AlterField(
            model_name="ilruns",
            name="category",
            field=models.CharField(max_length=30, verbose_name="Category ID"),
        ),
        migrations.AlterField(
            model_name="mainruns",
            name="category",
            field=models.CharField(max_length=30, verbose_name="Category ID"),
        ),
    ]
