# Generated by Django 5.1.7 on 2025-03-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0010_remove_mainruns_timeframes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilruns',
            name='arch_video',
            field=models.URLField(blank=True, help_text='Optional field. If you have a mirrored link to a video, you can input it here.', null=True, verbose_name='Archived Video URL'),
        ),
        migrations.AddField(
            model_name='ilruns',
            name='vid_status',
            field=models.CharField(default='verified', help_text='This is the current status of the run, according to Speedrun.com. It should be updated whenever the run is approved. Runs set as "Unverified" do not appear anywhere on this site.', verbose_name='SRC Status'),
        ),
        migrations.AddField(
            model_name='mainruns',
            name='arch_video',
            field=models.URLField(blank=True, help_text='Optional field. If you have a mirrored link to a video, you can input it here.', null=True, verbose_name='Archived Video URL'),
        ),
        migrations.AddField(
            model_name='mainruns',
            name='vid_status',
            field=models.CharField(default='verified', help_text='This is the current status of the run, according to Speedrun.com. It should be updated whenever the run is approved. Runs set as "Unverified" do not appear anywhere on this site.', verbose_name='SRC Status'),
        ),
    ]
