# Generated by Django 5.1.7 on 2025-03-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0011_ilruns_arch_video_ilruns_vid_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='location',
        ),
    ]
