# Generated by Django 4.2.1 on 2023-06-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0011_ilruns_subcategory_mainruns_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variables",
            name="gameid",
            field=models.CharField(
                default="", max_length=10, verbose_name="Linked Game"
            ),
            preserve_default=False,
        ),
    ]
