# Generated by Django 4.2.1 on 2023-06-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0012_variables_gameid"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainruns",
            name="playerid2",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Player 2 ID"
            ),
        ),
    ]
