# Generated by Django 5.1.7 on 2025-04-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0012_remove_players_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='bluesky',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Bluesky'),
        ),
    ]
