# Generated by Django 4.2.1 on 2023-06-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0013_mainruns_playerid2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainruns",
            name="playerid",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Player ID"
            ),
        ),
    ]
