# Generated by Django 5.1.7 on 2025-04-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0013_players_bluesky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilruns',
            name='vid_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('new', 'Unverified'), ('rejected', 'Rejected')], default='verified', help_text='This is the current status of the run, according to Speedrun.com. It should be updated whenever the run is approved. Runs set as "Unverified" do not appear anywhere on this site.', verbose_name='SRC Status'),
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='vid_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('new', 'Unverified'), ('rejected', 'Rejected')], default='verified', help_text='This is the current status of the run, according to Speedrun.com. It should be updated whenever the run is approved. Runs set as "Unverified" do not appear anywhere on this site.', verbose_name='SRC Status'),
        ),
    ]
