# Generated by Django 4.2.1 on 2023-06-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0014_alter_mainruns_playerid"),
    ]

    operations = [
        migrations.AddField(
            model_name="ilruns",
            name="time_secs",
            field=models.IntegerField(default=0, verbose_name="Time (Seconds)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mainruns",
            name="time_secs",
            field=models.IntegerField(default=0, verbose_name="Time (Seconds)"),
            preserve_default=False,
        ),
    ]
