# Generated by Django 5.1.7 on 2025-04-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0014_alter_ilruns_vid_status_alter_mainruns_vid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='bluesky',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Bluesky'),
        ),
    ]
