# Generated by Django 5.2 on 2025-04-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0015_alter_players_bluesky'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameoverview',
            name='twitch',
            field=models.CharField(max_length=55, null=True, verbose_name='Twitch Name'),
        ),
        migrations.AlterField(
            model_name='gameoverview',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Name'),
        ),
    ]
