# Generated by Django 4.2.1 on 2023-06-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0015_ilruns_time_secs_mainruns_time_secs"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="gameid",
            field=models.CharField(
                default="", max_length=10, verbose_name="Linked Game"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="levels",
            name="gameid",
            field=models.CharField(
                default="", max_length=10, verbose_name="Linked Game"
            ),
            preserve_default=False,
        ),
    ]
