# Generated by Django 5.2 on 2025-04-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0016_gameoverview_twitch_alter_gameoverview_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameoverview',
            name='twitch',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Twitch Name'),
        ),
    ]
