# Generated by Django 5.2 on 2025-04-06 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0017_alter_gameoverview_twitch'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowStreaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Twitch Title')),
                ('offline_ct', models.IntegerField(help_text='In some situations, bots or the Twitch API can mess up. To help users, you can use this counter to countup the number of attempts to see if the runner is offline. After a certain number is hit, you can do something like remove embeds and/or remove this record.', verbose_name='Offline Count')),
                ('stream_time', models.DateTimeField(verbose_name='Started Stream')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.gameoverview', verbose_name='Game')),
                ('streamer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.players', verbose_name='Streamer')),
            ],
            options={
                'verbose_name_plural': 'Streaming',
            },
        ),
    ]
