# Generated by Django 4.2.1 on 2023-06-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0017_newruns"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewWRs",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Run ID",
                    ),
                ),
                ("timeadded", models.DateTimeField(verbose_name="Time Added")),
            ],
            options={
                "verbose_name_plural": "Latest WRs",
            },
        ),
    ]
