# Generated by Django 4.2.1 on 2023-07-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0018_newwrs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ilruns",
            name="subcategory",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Subcategory Name"
            ),
        ),
        migrations.AlterField(
            model_name="ilruns",
            name="time",
            field=models.CharField(max_length=20, verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="ilruns",
            name="time_secs",
            field=models.FloatField(verbose_name="Time (Seconds)"),
        ),
        migrations.AlterField(
            model_name="mainruns",
            name="subcategory",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Subcategory Name"
            ),
        ),
        migrations.AlterField(
            model_name="mainruns",
            name="time",
            field=models.CharField(max_length=20, verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="mainruns",
            name="time_secs",
            field=models.FloatField(verbose_name="Time (Seconds)"),
        ),
    ]
