# Generated by Django 5.2 on 2025-04-06 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0018_nowstreaming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nowstreaming',
            name='id',
        ),
        migrations.AlterField(
            model_name='nowstreaming',
            name='streamer',
            field=models.OneToOneField(default='thepackle', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='srl.players', verbose_name='Streamer'),
            preserve_default=False,
        ),
    ]
