# Generated by Django 5.2 on 2025-04-10 03:11

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0019_remove_nowstreaming_id_alter_nowstreaming_streamer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilruns',
            name='values',
        ),
        migrations.RemoveField(
            model_name='mainruns',
            name='values',
        ),
        migrations.AlterField(
            model_name='ilruns',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='srl.categories', verbose_name='Category ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ilruns',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='srl.gameoverview', verbose_name='Game ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ilruns',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='srl.levels', verbose_name='Level ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ilruns',
            name='platform',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='srl.platforms', verbose_name='Platform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='srl.categories', verbose_name='Category ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='srl.gameoverview', verbose_name='Game ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='platform',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='srl.platforms', verbose_name='Platform'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Run ID')),
                ('runtype', models.CharField(choices=[('main', 'Full Game'), ('il', 'Individual Level')], max_length=5, verbose_name='Full-Game or IL')),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subcategory Name')),
                ('place', models.IntegerField(verbose_name='Placing')),
                ('url', models.URLField(verbose_name='URL')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Video')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Submitted Date')),
                ('v_date', models.DateTimeField(blank=True, null=True, verbose_name='Verified Date')),
                ('time', models.CharField(blank=True, max_length=25, null=True, verbose_name='RTA Time')),
                ('time_secs', models.FloatField(blank=True, null=True, verbose_name='RTA Time (Seconds)')),
                ('timenl', models.CharField(blank=True, max_length=25, null=True, verbose_name='LRT Time')),
                ('timenl_secs', models.FloatField(blank=True, null=True, verbose_name='LRT Time (Seconds)')),
                ('timeigt', models.CharField(blank=True, max_length=25, null=True, verbose_name='IGT Time')),
                ('timeigt_secs', models.FloatField(blank=True, null=True, verbose_name='IGT Time (Seconds)')),
                ('points', models.IntegerField(default=0, verbose_name='Packle Points')),
                ('emulated', models.BooleanField(default=False, verbose_name='Emulated?')),
                ('vid_status', models.CharField(choices=[('verified', 'Verified'), ('new', 'Unverified'), ('rejected', 'Rejected')], default='verified', help_text='This is the current status of the run, according to Speedrun.com. It should be updated whenever the run is approved. Runs set as "Unverified" do not appear anywhere on this site.', verbose_name='SRC Status')),
                ('obsolete', models.BooleanField(default=False, help_text="When True, the run will be considered obsolete. Points will not count towards the player's total.", verbose_name='Obsolete?')),
                ('arch_video', models.URLField(blank=True, help_text='Optional field. If you have a mirrored link to a video, you can input it here.', null=True, verbose_name='Archived Video URL')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.categories', verbose_name='Category ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srl.gameoverview', verbose_name='Game ID')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.levels', verbose_name='Level ID')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.platforms', verbose_name='Platform')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs_p1', to='srl.players', verbose_name='Player ID')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs_p2', to='srl.players', verbose_name='Player 2 ID')),
            ],
            options={
                'verbose_name_plural': 'Runs',
            },
        ),
        migrations.DeleteModel(
            name='MainRunTimeframe',
        ),
    ]
