# Generated by Django 4.2.5 on 2023-10-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0019_alter_ilruns_subcategory_alter_ilruns_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='countrycode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Country Code'),
        ),
    ]
