# Generated by Django 5.2 on 2025-04-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0020_remove_ilruns_values_remove_mainruns_values_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainruns',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mainruns',
            name='game',
        ),
        migrations.RemoveField(
            model_name='mainruns',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='mainruns',
            name='player',
        ),
        migrations.RemoveField(
            model_name='mainruns',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='gameoverview',
            name='abbr',
        ),
        migrations.AddField(
            model_name='gameoverview',
            name='slug',
            field=models.CharField(default='', max_length=20, verbose_name='Abbreviation/Slug'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ILRuns',
        ),
        migrations.DeleteModel(
            name='MainRuns',
        ),
    ]
