# Generated by Django 4.2.5 on 2023-10-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0020_players_countrycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCodes',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Country Code ID')),
                ('name', models.CharField(max_length=50, verbose_name='Country Name')),
            ],
            options={
                'verbose_name_plural': 'Country Codes',
            },
        ),
    ]
