# Generated by Django 4.2.5 on 2023-10-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0021_countrycodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='hidden',
            field=models.BooleanField(default='False', verbose_name='Hide Category'),
        ),
        migrations.AddField(
            model_name='variables',
            name='hidden',
            field=models.BooleanField(default='False', verbose_name='Hide Variables'),
        ),
    ]
