# Generated by Django 5.2 on 2025-04-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0021_remove_mainruns_category_remove_mainruns_game_and_more'),
    ]

    operations = [
    ]
