# Generated by Django 5.2 on 2025-04-12 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0022_merge_20250412_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameoverview',
            name='ipointsmax',
            field=models.IntegerField(default=100, help_text='Default is 100; 25 if this game contains the name "Category Extension". This is the maximum total of points an IL speedrun receives if it is the world record. All lower-ranked speedruns recieve less based upon an algorithmic formula.<br />                    NOTE: Changing this value will ONLY affect new runs. If you change this value, you will need to reset runs for this game from the admin panel.', verbose_name='IL WR Point Maximum'),
        ),
        migrations.AlterField(
            model_name='gameoverview',
            name='pointsmax',
            field=models.IntegerField(default=1000, help_text='Default is 1000; 25 if this game contains the name "Category Extension". This is the maximum total of points a full-game speedrun receives if it is the world record. All lower-ranked speedruns recieve less based upon an algorithmic formula.<br />                    NOTE: Changing this value will ONLY affect new runs. If you change this value, you will need to reset runs for this game from the admin panel.', verbose_name='Full Game WR Point Maximum'),
        ),
        migrations.AlterField(
            model_name='players',
            name='nickname',
            field=models.CharField(blank=True, help_text='This is a special field where,  if a nickname is given,  it will be shown versus their SRC name.', max_length=30, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='runs',
            name='arch_video',
            field=models.URLField(blank=True, help_text='Optional field. If you have a mirrored link to a video,  you can input it here.', null=True, verbose_name='Archived Video URL'),
        ),
        migrations.AlterField(
            model_name='runs',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.levels', verbose_name='Level ID'),
        ),
        migrations.AlterField(
            model_name='runs',
            name='obsolete',
            field=models.BooleanField(default=False, help_text="When True,  the run will be considered obsolete. Points will not count towards the player's total.", verbose_name='Obsolete?'),
        ),
        migrations.AlterField(
            model_name='runs',
            name='vid_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('new', 'Unverified'), ('rejected', 'Rejected')], default='verified', help_text='This is the current status of the run,  according to Speedrun.com. It should be updated whenever the run is approved. Runs set as "Unverified" do not appear anywhere on this site.', verbose_name='SRC Status'),
        ),
        migrations.AlterField(
            model_name='variables',
            name='all_cats',
            field=models.BooleanField(default=False, help_text='When checked,  this means that the variable will work across all categories of the game in the "Game" field. Note: The "Linked Category" must be blank.', verbose_name='All Categories'),
        ),
        migrations.CreateModel(
            name='RunVariableValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srl.runs')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srl.variablevalues')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srl.variables')),
            ],
        ),
        migrations.AddField(
            model_name='runs',
            name='variables',
            field=models.ManyToManyField(related_name='runs', through='srl.RunVariableValues', to='srl.variables', verbose_name='Variables'),
        ),
        migrations.AddConstraint(
            model_name='runvariablevalues',
            constraint=models.UniqueConstraint(fields=('run', 'variable'), name='unique_variable_and_value'),
        ),
    ]
