# Generated by Django 4.2.5 on 2023-10-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0022_categories_hidden_variables_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablevalues',
            name='hidden',
            field=models.BooleanField(default='False', verbose_name='Hide Value'),
        ),
    ]
