# Generated by Django 5.2 on 2025-04-12 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0023_alter_gameoverview_ipointsmax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.categories', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='runs',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srl.gameoverview', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='runs',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.levels', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='runs',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs_p1', to='srl.players', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='runs',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs_p2', to='srl.players', verbose_name='Player 2'),
        ),
    ]
