# Generated by Django 4.2.9 on 2024-01-30 17:57

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import srl.models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0023_variablevalues_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Award Name')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, help_text='Note: Images must be at least 64px in size, must be a square (height and width must match), and the max filesize is 3MB.', keep_meta=True, null=True, quality=-1, scale=None, size=[64, 64], upload_to='srl/static/srl/imgs/awards', validators=[srl.models.validate_image], verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Award Description')),
                ('unique', models.BooleanField(default=False, help_text="When checked, this award will be given the 'unique' tag - enabling special effects for the award on the profile page.", verbose_name='Unique Award')),
            ],
            options={
                'verbose_name_plural': 'Awards',
            },
        ),
        migrations.AddField(
            model_name='ilruns',
            name='obsolete',
            field=models.BooleanField(default=False, help_text="When True, the run will be considered obsolete. Points will not count towards the player's total.", verbose_name='Obsolete?'),
        ),
        migrations.AddField(
            model_name='ilruns',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='mainruns',
            name='obsolete',
            field=models.BooleanField(default=False, help_text="When True, the run will be considered obsolete. Points will not count towards the player's total.", verbose_name='Obsolete?'),
        ),
        migrations.AddField(
            model_name='mainruns',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='players',
            name='ex_stream',
            field=models.BooleanField(default=False, help_text='When checked, this player can be filtered out from appearing on stream bots or pages.', verbose_name='Stream Exception'),
        ),
        migrations.AddField(
            model_name='players',
            name='nickname',
            field=models.CharField(blank=True, help_text='This is a special field where, if a nickname is given, it will be shown versus their SRC name.', max_length=30, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='gameid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.gameoverview', verbose_name='Linked Game'),
        ),
        migrations.AlterField(
            model_name='ilruns',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.categories', verbose_name='Category ID'),
        ),
        migrations.AlterField(
            model_name='ilruns',
            name='gameid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.gameoverview', verbose_name='Game ID'),
        ),
        migrations.AlterField(
            model_name='ilruns',
            name='levelid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.levels', verbose_name='Level ID'),
        ),
        migrations.AlterField(
            model_name='ilruns',
            name='playerid',
            field=models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.SET_DEFAULT, to='srl.players', verbose_name='Player ID'),
        ),
        migrations.AlterField(
            model_name='levels',
            name='gameid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.gameoverview', verbose_name='Linked Game'),
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.categories', verbose_name='Category ID'),
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='gameid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.gameoverview', verbose_name='Game ID'),
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='playerid',
            field=models.ForeignKey(blank=True, default='Anonymous', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='main_runs', to='srl.players', verbose_name='Player ID'),
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='playerid2',
            field=models.ForeignKey(blank=True, default='Anonymous', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='main_runs_p2', to='srl.players', verbose_name='Player 2 ID'),
        ),
        migrations.AlterField(
            model_name='players',
            name='countrycode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.countrycodes', verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='players',
            name='pfp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Profile Picture URL'),
        ),
        migrations.AlterField(
            model_name='players',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='variables',
            name='gameid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.gameoverview', verbose_name='Linked Game'),
        ),
        migrations.AlterField(
            model_name='variablevalues',
            name='id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.variables', verbose_name='Linked Variable'),
        ),
        migrations.AddField(
            model_name='players',
            name='awards',
            field=models.ManyToManyField(blank=True, default=False, help_text="Earned awards can be selected here. All selected awards will appear on the Player's profile.", to='srl.awards', verbose_name='Awards'),
        ),
    ]
