# Generated by Django 4.2.9 on 2024-02-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0024_awards_ilruns_obsolete_ilruns_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='gameid',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='ilruns',
            old_name='gameid',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='ilruns',
            old_name='levelid',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='ilruns',
            old_name='playerid',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='levels',
            old_name='gameid',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='mainruns',
            old_name='gameid',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='mainruns',
            old_name='playerid',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='mainruns',
            old_name='playerid2',
            new_name='player2',
        ),
        migrations.RenameField(
            model_name='variables',
            old_name='gameid',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='variablevalues',
            old_name='valueid',
            new_name='value',
        ),
        migrations.AddField(
            model_name='variables',
            name='all_cats',
            field=models.BooleanField(default=False, help_text='When checked, this means that the variable will work across all categories of the game in the "Game" field. Note: The "Linked Category" must be blank.', verbose_name='All Categories'),
        ),
        migrations.AlterField(
            model_name='variables',
            name='cat',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Linked Category'),
        ),
    ]
