# Generated by Django 5.2 on 2025-04-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0024_alter_runs_category_alter_runs_game_alter_runs_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='countrycodes',
            options={'ordering': ['name'], 'verbose_name_plural': 'Country Codes'},
        ),
        migrations.AlterModelOptions(
            name='gameoverview',
            options={'ordering': ['release'], 'verbose_name_plural': 'Game Overview'},
        ),
        migrations.AlterModelOptions(
            name='levels',
            options={'ordering': ['name'], 'verbose_name_plural': 'Levels'},
        ),
        migrations.AlterModelOptions(
            name='platforms',
            options={'ordering': ['name'], 'verbose_name_plural': 'Platforms'},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'ordering': ['name'], 'verbose_name_plural': 'Players'},
        ),
    ]
