# Generated by Django 5.2 on 2025-04-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0025_alter_categories_options_alter_countrycodes_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameOverview',
            new_name='Games',
        ),
        migrations.AlterField(
            model_name='runs',
            name='arch_video',
            field=models.URLField(blank=True, help_text='Optional field. If you have a mirrored link to a video, you can input it here.', null=True, verbose_name='Archived Video URL'),
        ),
        migrations.AlterField(
            model_name='runs',
            name='obsolete',
            field=models.BooleanField(default=False, help_text="When True, the run will be considered obsolete. Points will not count towards the player's total.", verbose_name='Obsolete?'),
        ),
        migrations.AlterField(
            model_name='runs',
            name='vid_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('new', 'Unverified'), ('rejected', 'Rejected')], default='verified', help_text='This is the current status of the run, according to Speedrun.com. It should be updated whenever the run is approved. Runs set as "Unverified" or "Rejected" do not appear anywhere on this site.', verbose_name='SRC Status'),
        ),
    ]
