# Generated by Django 4.2.9 on 2024-02-02 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0025_rename_gameid_categories_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variablevalues',
            old_name='id',
            new_name='var',
        ),
    ]
