# Generated by Django 5.2 on 2025-04-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0026_rename_gameoverview_games_alter_runs_arch_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'ordering': ['release'], 'verbose_name_plural': 'Games'},
        ),
    ]
