# Generated by Django 4.2.9 on 2024-02-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0026_rename_id_variablevalues_var'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Platform ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Platforms',
            },
        ),
        migrations.AddField(
            model_name='ilruns',
            name='timeigt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IGT Time'),
        ),
        migrations.AddField(
            model_name='ilruns',
            name='timeigt_secs',
            field=models.FloatField(blank=True, null=True, verbose_name='IGT Time (Seconds)'),
        ),
        migrations.AddField(
            model_name='ilruns',
            name='timenl',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='LRT Time'),
        ),
        migrations.AddField(
            model_name='ilruns',
            name='timenl_secs',
            field=models.FloatField(blank=True, null=True, verbose_name='LRT Time (Seconds)'),
        ),
        migrations.AddField(
            model_name='mainruns',
            name='timeigt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IGT Time'),
        ),
        migrations.AddField(
            model_name='mainruns',
            name='timeigt_secs',
            field=models.FloatField(blank=True, null=True, verbose_name='IGT Time (Seconds)'),
        ),
        migrations.AddField(
            model_name='mainruns',
            name='timenl',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='LRT Time'),
        ),
        migrations.AddField(
            model_name='mainruns',
            name='timenl_secs',
            field=models.FloatField(blank=True, null=True, verbose_name='LRT Time (Seconds)'),
        ),
        migrations.AlterField(
            model_name='ilruns',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RTA Time'),
        ),
        migrations.AlterField(
            model_name='ilruns',
            name='time_secs',
            field=models.FloatField(blank=True, null=True, verbose_name='RTA Time (Seconds)'),
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Packle Points'),
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RTA Time'),
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='time_secs',
            field=models.FloatField(blank=True, null=True, verbose_name='RTA Time (Seconds)'),
        ),
    ]
