# Generated by Django 5.2 on 2025-04-13 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0027_alter_games_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to='srl.players', verbose_name='Approver'),
        ),
        migrations.AddField(
            model_name='runs',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
    ]
