# Generated by Django 4.2.9 on 2024-02-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0027_platforms_ilruns_timeigt_ilruns_timeigt_secs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameoverview',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Name'),
        ),
    ]
