# Generated by Django 5.2 on 2025-04-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0028_runs_approver_runs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='ipointsmax',
            field=models.IntegerField(default=100, help_text='Default is 100; 25 if this game contains the name "Category Extension". This is the maximum total of points an IL speedrun receives if it is the world record. All lower-ranked speedruns recieve less based upon an algorithmic formula.<br />NOTE: Changing this value will ONLY affect new runs. If you change this value, you will need to reset runs for this game from the admin panel.', verbose_name='IL WR Point Maximum'),
        ),
        migrations.AlterField(
            model_name='games',
            name='pointsmax',
            field=models.IntegerField(default=1000, help_text='Default is 1000; 25 if this game contains the name "Category Extension". This is the maximum total of points a full-game speedrun receives if it is the world record. All lower-ranked speedruns recieve less based upon an algorithmic formula.<br />NOTE: Changing this value will ONLY affect new runs. If you change this value, you will need to reset runs for this game from the admin panel.', verbose_name='Full Game WR Point Maximum'),
        ),
        migrations.AlterField(
            model_name='players',
            name='nickname',
            field=models.CharField(blank=True, help_text='This is a special field where,  if a nickname is given, it will be shown versus their SRC name.', max_length=30, null=True, verbose_name='Nickname'),
        ),
    ]
