# Generated by Django 4.2.9 on 2024-02-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0028_alter_gameoverview_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameoverview',
            name='platforms',
            field=models.CharField(max_length=300, verbose_name='Platforms'),
        ),
    ]
