# Generated by Django 4.2.9 on 2024-02-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0029_alter_gameoverview_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
