# Generated by Django 5.2 on 2025-04-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0029_alter_games_ipointsmax_alter_games_pointsmax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awards',
            name='unique',
        ),
        migrations.AlterField(
            model_name='categories',
            name='type',
            field=models.CharField(choices=[('per-level', 'Individual Level'), ('per-game', 'Full Game')], verbose_name='Type (IL/FG)'),
        ),
    ]
