# Generated by Django 4.2.9 on 2024-02-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0030_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
