# Generated by Django 5.2 on 2025-04-29 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0030_remove_awards_unique_alter_categories_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nowstreaming',
            options={'verbose_name': 'Stream', 'verbose_name_plural': 'Streams'},
        ),
        migrations.AlterModelOptions(
            name='runvariablevalues',
            options={'verbose_name_plural': 'Run Variable Values'},
        ),
        migrations.AddField(
            model_name='variables',
            name='level',
            field=models.ForeignKey(blank=True, help_text='If "scope" is set to "single-level", then a level must be associated. Otherwise, keep null.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.levels', verbose_name='Associated Level'),
        ),
        migrations.AlterField(
            model_name='players',
            name='bluesky',
            field=models.URLField(blank=True, null=True, verbose_name='Bluesky'),
        ),
        migrations.AlterField(
            model_name='players',
            name='pfp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profile Picture URL'),
        ),
        migrations.AlterField(
            model_name='players',
            name='twitch',
            field=models.URLField(blank=True, null=True, verbose_name='Twitch'),
        ),
        migrations.AlterField(
            model_name='players',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='players',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='variables',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hide Variable'),
        ),
        migrations.AlterField(
            model_name='variables',
            name='scope',
            field=models.CharField(choices=[('global', 'All Categories'), ('full-game', 'Only Full Game Runs'), ('all-levels', 'Only IL Runs'), ('single-level', 'Specific IL')], verbose_name='Scope (FG/IL)'),
        ),
    ]
