# Generated by Django 4.2.9 on 2024-02-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0031_alter_levels_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='name',
            field=models.CharField(max_length=75, verbose_name='Name'),
        ),
    ]
