# Generated by Django 5.2.1 on 2025-05-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0031_alter_nowstreaming_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='rules',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Rules'),
        ),
        migrations.AddField(
            model_name='levels',
            name='rules',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Rules'),
        ),
        migrations.AddField(
            model_name='variablevalues',
            name='rules',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Rules'),
        ),
    ]
