# Generated by Django 4.2.9 on 2024-02-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0032_alter_levels_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilruns',
            name='platform',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='ilruns',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subcategory Name'),
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='platform',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subcategory Name'),
        ),
        migrations.AlterField(
            model_name='variables',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='variablevalues',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
