# Generated by Django 5.2.3 on 2025-06-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0032_categories_rules_levels_rules_variablevalues_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='awards',
            field=models.ManyToManyField(blank=True, help_text="Earned awards can be selected here. All selected awards will appear on the Player's profile.", to='srl.awards', verbose_name='Awards'),
        ),
    ]
