# Generated by Django 4.2.9 on 2024-02-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0033_alter_ilruns_platform_alter_ilruns_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='twitch',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Twitch'),
        ),
    ]
