# Generated by Django 4.2.9 on 2024-02-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0035_alter_players_twitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilruns',
            name='time',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='RTA Time'),
        ),
        migrations.AlterField(
            model_name='ilruns',
            name='timeigt',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='IGT Time'),
        ),
        migrations.AlterField(
            model_name='ilruns',
            name='timenl',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='LRT Time'),
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='time',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='RTA Time'),
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='timeigt',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='IGT Time'),
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='timenl',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='LRT Time'),
        ),
    ]
