# Generated by Django 4.2.9 on 2024-02-10 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0036_alter_ilruns_time_alter_ilruns_timeigt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilruns',
            name='emulated',
            field=models.BooleanField(default=False, verbose_name='Emulated?'),
        ),
        migrations.AddField(
            model_name='mainruns',
            name='emulated',
            field=models.BooleanField(default=False, verbose_name='Emulated?'),
        ),
        migrations.AlterField(
            model_name='ilruns',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.platforms', verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='ilruns',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Packle Points'),
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.platforms', verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='mainruns',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Packle Points'),
        ),
    ]
