# Generated by Django 4.2.9 on 2024-02-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0037_ilruns_emulated_mainruns_emulated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameoverview',
            name='platforms',
        ),
        migrations.AddField(
            model_name='gameoverview',
            name='platforms',
            field=models.ManyToManyField(null=True, to='srl.platforms', verbose_name='Platforms'),
        ),
    ]
