# Generated by Django 4.2.5 on 2024-05-10 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("srl", "0038_remove_gameoverview_platforms_gameoverview_platforms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hide Category"),
        ),
        migrations.AlterField(
            model_name="gameoverview",
            name="platforms",
            field=models.ManyToManyField(to="srl.platforms", verbose_name="Platforms"),
        ),
        migrations.AlterField(
            model_name="ilruns",
            name="player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="srl.players",
                verbose_name="Player ID",
            ),
        ),
        migrations.AlterField(
            model_name="mainruns",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_runs",
                to="srl.players",
                verbose_name="Player ID",
            ),
        ),
        migrations.AlterField(
            model_name="mainruns",
            name="player2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_runs_p2",
                to="srl.players",
                verbose_name="Player 2 ID",
            ),
        ),
        migrations.AlterField(
            model_name="players",
            name="name",
            field=models.CharField(
                default="Anonymous", max_length=30, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="variables",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hide Variables"),
        ),
        migrations.AlterField(
            model_name="variablevalues",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hide Value"),
        ),
    ]
