# Generated by Django 5.1.1 on 2024-10-14 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0039_alter_categories_hidden_alter_gameoverview_platforms_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainRunTimeframe",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateTimeField(verbose_name="Approved Date")),
                ("end_date", models.DateTimeField(verbose_name="Beaten Date")),
                (
                    "points",
                    models.IntegerField(default=0, verbose_name="Packle Points"),
                ),
                (
                    "run_id",
                    models.ForeignKey(
                        max_length=10,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="srl.mainruns",
                        verbose_name="Run ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Main Run Timeframes",
            },
        ),
        migrations.AddField(
            model_name="ilruns",
            name="timeframes",
            field=models.ManyToManyField(
                blank=True,
                default=False,
                help_text="This is a list of all the timeframes this run held certain point values; upon being beaten by that player or another, this is updated.",
                to="srl.mainruntimeframe",
                verbose_name="Run Timeframes",
            ),
        ),
        migrations.AddField(
            model_name="mainruns",
            name="timeframes",
            field=models.ManyToManyField(
                blank=True,
                default=False,
                help_text="This is a list of all the timeframes this run held certain point values; upon being beaten by that player or another, this is updated.",
                to="srl.mainruntimeframe",
                verbose_name="Run Timeframes",
            ),
        ),
    ]
