# Generated by Django 5.1 on 2024-10-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0039_alter_categories_hidden_alter_gameoverview_platforms_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainRunTimeframe",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Run ID",
                    ),
                ),
                ("approve_date", models.DateTimeField(verbose_name="Approved Date")),
                ("beaten_date", models.DateTimeField(verbose_name="Beaten Date")),
            ],
            options={
                "verbose_name_plural": "Run Timeframes",
            },
        ),
        migrations.AddField(
            model_name="ilruns",
            name="timeframes",
            field=models.ManyToManyField(
                blank=True,
                default=False,
                help_text="This is a list of all the timeframes this run held certain point values; upon being beaten by that player or another, this is updated.",
                to="srl.MainRunTimeframe",
                verbose_name="Run Timeframes",
            ),
        ),
        migrations.AddField(
            model_name="mainruns",
            name="timeframes",
            field=models.ManyToManyField(
                blank=True,
                default=False,
                help_text="This is a list of all the timeframes this run held certain point values; upon being beaten by that player or another, this is updated.",
                to="srl.MainRunTimeframe",
                verbose_name="Run Timeframes",
            ),
        ),
    ]
