# Generated by Django 5.1.1 on 2024-10-14 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0040_mainruntimeframe_ilruns_timeframes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variables",
            name="cat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="srl.categories",
                verbose_name="Category",
            ),
        ),
    ]
