# Generated by Django 5.1.1 on 2024-10-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0041_alter_variables_cat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variablevalues",
            name="var",
        ),
        migrations.AddField(
            model_name="variablevalues",
            name="var",
            field=models.ManyToManyField(
                to="srl.variables", verbose_name="Linked Variable"
            ),
        ),
    ]
