# Generated by Django 5.1.1 on 2024-10-14 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0042_remove_variablevalues_var_variablevalues_var"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variablevalues",
            name="var",
        ),
        migrations.AddField(
            model_name="variablevalues",
            name="var",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="srl.variables",
                verbose_name="Linked Variable",
            ),
        ),
    ]
