# Generated by Django 5.1.1 on 2024-10-18 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0043_remove_variablevalues_var_variablevalues_var"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ilruns",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="srl.players",
                verbose_name="Player ID",
            ),
        ),
    ]
