# Generated by Django 5.2.5 on 2025-08-26 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('srl', '0010_remove_old_player_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tag Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Guide Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(help_text='Brief description of what this guide covers.', max_length=500, verbose_name='Short Description')),
                ('content', models.TextField(help_text='Full guide content; markdown is allowed.', verbose_name='Guide Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At:')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srl.games', verbose_name='Associated Game')),
                ('tags', models.ManyToManyField(blank=True, to='guides.tags', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Guides',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
