# Generated by Django 6.0.8 on 2026-08-28 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0003_guides_owner"),
        ("srl", "0063_backfill_required_methods"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="guides",
            name="slug",
            field=models.SlugField(max_length=200, verbose_name="Slug"),
        ),
        migrations.AddConstraint(
            model_name="guides",
            constraint=models.UniqueConstraint(
                fields=("game", "slug"), name="unique_guide_slug_per_game"
            ),
        ),
    ]
