# Generated by Django 5.2.4 on 2025-08-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0003_alter_variablevalues_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="slug",
            field=models.SlugField(max_length=50, blank=True, verbose_name="Slug"),
        ),
        migrations.AddField(
            model_name="levels",
            name="slug",
            field=models.SlugField(max_length=75, blank=True, verbose_name="Slug"),
        ),
        migrations.AddField(
            model_name="platforms",
            name="slug",
            field=models.SlugField(max_length=20, blank=True, verbose_name="Slug"),
        ),
        migrations.AddField(
            model_name="variables",
            name="slug",
            field=models.SlugField(max_length=50, blank=True, verbose_name="Slug"),
        ),
        migrations.AddField(
            model_name="variablevalues",
            name="slug",
            field=models.SlugField(max_length=50, blank=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="games",
            name="slug",
            field=models.SlugField(max_length=20, verbose_name="Slug"),
        ),
    ]
