# Generated by Django 5.2.4 on 2025-08-18 16:38

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    models_to_slugify = [
        "Categories",
        "Levels",
        "Platforms",
        "Variables",
        "VariableValues",
    ]

    symbol_exemptions = {
        "+": "-plus",
        "&": "-and",
        "/": "-",
    }

    for model_name in models_to_slugify:
        Model = apps.get_model("srl", model_name)
        for obj in Model.objects.all():
            slug = obj.name
            for old, new in symbol_exemptions.items():
                slug = slug.replace(old, new)

            slug = slugify(slug)
            obj.slug = slug
            obj.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0004_categories_slug_levels_slug_platforms_slug_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
