# Generated by Django 5.2.5 on 2025-08-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0005_auto_20250818_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='slug',
            field=models.SlugField(max_length=20, verbose_name='Abbreviation/Slug'),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, verbose_name='Slug'),
        ),
    ]
