# Generated by Django 5.2.5 on 2025-08-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0006_alter_games_slug_alter_platforms_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variables',
            name='scope',
            field=models.CharField(choices=[('global', 'Entire Game'), ('full-game', 'Only Full Game Runs'), ('all-levels', 'Only IL Runs'), ('single-level', 'Specific IL')], verbose_name='Scope (FG/IL)'),
        ),
    ]
