# Generated by Django 5.2.5 on 2025-08-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0007_alter_variables_scope"),
    ]

    operations = [
        # Create the new RunPlayers through model
        migrations.CreateModel(
            name="RunPlayers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Order of this player in the run (1 for primary player, 2 for secondary, etc.)",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_runs",
                        to="srl.players",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_players",
                        to="srl.runs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Run Player",
                "verbose_name_plural": "Run Players",
                "ordering": ["run", "player__name"],
            },
        ),
        # Add the unique constraint
        migrations.AddConstraint(
            model_name="runplayers",
            constraint=models.UniqueConstraint(
                fields=("run", "player"), name="unique_run_player"
            ),
        ),
        # Add the new players ManyToMany field
        migrations.AddField(
            model_name="runs",
            name="players",
            field=models.ManyToManyField(
                blank=True,
                help_text="Players who participated in this run. If no players are specified, the run will be displayed as Anonymous.",
                related_name="runs",
                through="srl.RunPlayers",
                to="srl.players",
                verbose_name="Players",
            ),
        ),
    ]
