# Generated by Django 5.2.5 on 2025-08-24

from django.db import migrations


def transfer_players_to_through_model(apps, schema_editor):
    """Transfer existing player/player2 data to the new RunPlayers through model."""
    Runs = apps.get_model("srl", "Runs")
    RunPlayers = apps.get_model("srl", "RunPlayers")

    total_runs = 0
    runs_with_player1 = 0
    runs_with_player2 = 0
    run_players_created = 0

    for run in Runs.objects.all():
        total_runs += 1

        if run.player:
            RunPlayers.objects.create(run=run, player=run.player, order=1)
            runs_with_player1 += 1
            run_players_created += 1

        if run.player2:
            RunPlayers.objects.create(run=run, player=run.player2, order=2)
            runs_with_player2 += 1
            run_players_created += 1


def reverse_transfer_players(apps, schema_editor):
    """Reverse migration - transfer RunPlayers data back to player/player2 fields."""
    Runs = apps.get_model("srl", "Runs")
    RunPlayers = apps.get_model("srl", "RunPlayers")

    for run in Runs.objects.all():
        run_players = RunPlayers.objects.filter(run=run).order_by("order")

        if run_players.exists():
            if len(run_players) >= 1:
                run.player = run_players[0].player
            if len(run_players) >= 2:
                run.player2 = run_players[1].player

            run.save()


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0008_runplayers_alter_runs_players"),
    ]

    operations = [
        migrations.RunPython(
            code=transfer_players_to_through_model,
            reverse_code=reverse_transfer_players,
        ),
    ]
