# Generated by Django 5.2.5 on 2025-08-24

from django.db import migrations


def transfer_players_to_through_model(apps, schema_editor):
    """
    Transfer existing player/player2 data to the new RunPlayers through model.

    This migration will:
    1. Go through every run in the Runs model
    2. Create RunPlayers entries for each player/player2
    3. Set appropriate order values (1 for player, 2 for player2)
    """
    # Get model classes (use historical versions from the migration state)
    Runs = apps.get_model("srl", "Runs")
    RunPlayers = apps.get_model("srl", "RunPlayers")

    # Track statistics
    total_runs = 0
    runs_with_player1 = 0
    runs_with_player2 = 0
    run_players_created = 0

    # Process all runs
    for run in Runs.objects.all():
        total_runs += 1

        # Handle player (primary player)
        if run.player:
            RunPlayers.objects.create(run=run, player=run.player, order=1)
            runs_with_player1 += 1
            run_players_created += 1

        # Handle player2 (secondary player)
        if run.player2:
            RunPlayers.objects.create(run=run, player=run.player2, order=2)
            runs_with_player2 += 1
            run_players_created += 1

    # Print migration statistics
    print("\n=== Player Data Transfer Statistics ===")
    print(f"Total runs processed: {total_runs}")
    print(f"Runs with primary player: {runs_with_player1}")
    print(f"Runs with secondary player: {runs_with_player2}")
    print(f"Total RunPlayers entries created: {run_players_created}")
    print(f"Anonymous runs (no players): {total_runs - runs_with_player1}")
    print("=== Transfer Complete ===\n")


def reverse_transfer_players(apps, schema_editor):
    """
    Reverse migration - transfer RunPlayers data back to player/player2 fields.

    Note: This is a lossy operation if runs have more than 2 players.
    Only the first two players (by order) will be preserved.
    """
    # Get model classes
    Runs = apps.get_model("srl", "Runs")
    RunPlayers = apps.get_model("srl", "RunPlayers")

    # Process all runs
    for run in Runs.objects.all():
        # Get players ordered by their order field
        run_players = RunPlayers.objects.filter(run=run).order_by("order")

        # Set player (order 1) and player2 (order 2) if they exist
        if run_players.exists():
            if len(run_players) >= 1:
                run.player = run_players[0].player
            if len(run_players) >= 2:
                run.player2 = run_players[1].player

            # Save the run with updated player fields
            run.save()

    print("\n=== Reverse Transfer Complete ===")
    print("Player/player2 fields have been restored from RunPlayers data")
    print("Note: Runs with more than 2 players lost additional player data")
    print("=====================================\n")


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0008_runplayers_alter_runs_players"),
    ]

    operations = [
        migrations.RunPython(
            code=transfer_players_to_through_model,
            reverse_code=reverse_transfer_players,
        ),
    ]
