# Generated by Django 5.2.5 on 2025-08-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0009_transfer_player_data_to_runplayers"),
    ]

    operations = [
        # Remove the old player and player2 fields from Runs model
        migrations.RemoveField(
            model_name="runs",
            name="player",
        ),
        migrations.RemoveField(
            model_name="runs",
            name="player2",
        ),
    ]
