# Generated by Django 5.2.5 on 2025-08-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0010_remove_old_player_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='defaulttime',
            field=models.CharField(choices=[('realtime', 'RTA'), ('realtime_noloads', 'LRT'), ('ingame', 'IGT')], default=None, help_text=("When not set, the category's associated game's timing method(s) are used. ", 'When used, the timing method for the ENTIRE category will take take precedence ', "over what is set for the category's associated game. ALL requests will use this to ", 'determine what timing method is used for the category.'), null=True, verbose_name='Default Time'),
        ),
    ]
