# Generated by Django 6.0 on 2026-01-15 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0011_categories_defaulttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='variables',
            name='all_cats',
        ),
        migrations.RemoveField(
            model_name='variables',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='variablevalues',
            name='hidden',
        ),
        migrations.AddField(
            model_name='categories',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archive Category'),
        ),
        migrations.AddField(
            model_name='levels',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archive Level'),
        ),
        migrations.AddField(
            model_name='variables',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archive Variable'),
        ),
        migrations.AddField(
            model_name='variablevalues',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archive Value'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='defaulttime',
            field=models.CharField(choices=[('realtime', 'RTA'), ('realtime_noloads', 'LRT'), ('ingame', 'IGT')], default=None, help_text="When not set, the category's associated game's timing method(s) are used. When used, the timing method for the ENTIRE category will take take precedence over what is set for the category's associated game. ALL requests will use this to determine what timing method is used for the category.", null=True, verbose_name='Default Time'),
        ),
        migrations.AlterField(
            model_name='variables',
            name='cat',
            field=models.ForeignKey(blank=True, help_text='If not set, the variable  is seen as a "global" variable for the scope you choose below. For example: a "global" variable set for "Only IL Runs" will make it a GLOBAL variable for IL speedruns.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='srl.categories', verbose_name='Category'),
        ),
    ]
