# Generated by Django 6.0 on 2026-01-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0012_remove_categories_hidden_remove_variables_all_cats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runplayers',
            options={'ordering': ['run', 'order'], 'verbose_name': 'Run Player', 'verbose_name_plural': 'Run Players'},
        ),
        migrations.AddField(
            model_name='runplayers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this player-run association was created.', null=True),
        ),
    ]
