# Generated by Django 6.0.1 on 2026-01-30 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0014_categories_created_at_categories_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Period Start')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Period End')),
                ('points', models.IntegerField(verbose_name='Points During Period')),
                ('end_reason', models.CharField(blank=True, choices=[('new_wr', 'New World Record'), ('lost_wr', 'Lost World Record'), ('gained_wr', 'Gained World Record'), ('obsoleted', 'Run Obsoleted')], max_length=20, null=True, verbose_name='End Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='srl.runs', verbose_name='Run')),
            ],
            options={
                'verbose_name': 'Run History',
                'verbose_name_plural': 'Run History',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='srl_runhist_start_d_0f56e2_idx'), models.Index(fields=['run', 'start_date'], name='srl_runhist_run_id_f8efeb_idx')],
            },
        ),
    ]
