# Generated by Django 6.0.1 on 2026-02-05 02:25

from django.db import migrations, models

# New point constants
POINTS_MAX_FG = 1000
POINTS_MAX_IL = 250
POINTS_MAX_CE = 50


def update_games_point_values(
    apps,
    _schema_editor,
):
    """Update all Games with new point values based on whether they are Category Extensions."""
    Games = apps.get_model("srl", "Games")

    for game in Games.objects.all():
        is_ce = "category extension" in game.name.lower()
        if is_ce:
            game.pointsmax = POINTS_MAX_CE
            game.ipointsmax = POINTS_MAX_CE
        else:
            game.pointsmax = POINTS_MAX_FG
            game.ipointsmax = POINTS_MAX_IL
        game.save(update_fields=["pointsmax", "ipointsmax"])


def reverse_games_point_values(
    apps,
    _schema_editor,
):
    """Reverse migration - restore old point values (1000/100/25 scheme)."""
    Games = apps.get_model("srl", "Games")

    for game in Games.objects.all():
        is_ce = "category extension" in game.name.lower()
        if is_ce:
            game.pointsmax = 25
            game.ipointsmax = 25
        else:
            game.pointsmax = 1000
            game.ipointsmax = 100
        game.save(update_fields=["pointsmax", "ipointsmax"])


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0015_runhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="runs",
            name="bonus",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Usually used to count the number of months (up to 4) a run has been the record.",
                verbose_name="Streak Bonus",
            ),
        ),
        migrations.AlterField(
            model_name="games",
            name="ipointsmax",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text='Default is 250; 25 if this game contains the name "Category Extension". This is the maximum total of points an IL speedrun receives if it is the world record. All lower-ranked speedruns recieve less based upon an algorithmic formula.<br />NOTE: Changing this value will ONLY affect new runs. If you change this value, you will need to reset runs for this game from the admin panel.',
                verbose_name="IL WR Point Maximum",
            ),
        ),
        migrations.AlterField(
            model_name="games",
            name="pointsmax",
            field=models.PositiveSmallIntegerField(
                default=1000,
                help_text='Default is 1000; 25 if this game contains the name "Category Extension". This is the maximum total of points a full-game speedrun receives if it is the world record. All lower-ranked speedruns recieve less based upon an algorithmic formula.<br />NOTE: Changing this value will ONLY affect new runs. If you change this value, you will need to reset runs for this game from the admin panel.',
                verbose_name="Full Game WR Point Maximum",
            ),
        ),
        migrations.AlterField(
            model_name="nowstreaming",
            name="offline_ct",
            field=models.PositiveSmallIntegerField(
                help_text="In some situations, bots or the Twitch API can mess up. To help users, you can use this counter to countup the number of attempts to see if the runner is offline. After a certain number is hit, you can do something like remove embeds and/or remove this record.",
                verbose_name="Offline Count",
            ),
        ),
        migrations.AlterField(
            model_name="runhistory",
            name="end_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new_wr", "New World Record"),
                    ("lost_wr", "Lost World Record"),
                    ("gained_wr", "Gained World Record"),
                    ("obsoleted", "Run Obsoleted"),
                    ("recalculation", "Points Recalculated"),
                ],
                max_length=20,
                null=True,
                verbose_name="End Reason",
            ),
        ),
        migrations.AlterField(
            model_name="runhistory",
            name="points",
            field=models.PositiveSmallIntegerField(verbose_name="Points During Period"),
        ),
        migrations.AlterField(
            model_name="runs",
            name="place",
            field=models.PositiveSmallIntegerField(verbose_name="Placing"),
        ),
        migrations.AlterField(
            model_name="runs",
            name="points",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Packle Points"
            ),
        ),
        migrations.RunPython(
            update_games_point_values,
            reverse_code=reverse_games_point_values,
        ),
    ]
