# Generated by Django 6.0.2 on 2026-02-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0016_runs_bonus_alter_games_ipointsmax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablevalues',
            name='appear_on_main',
            field=models.BooleanField(default=True, help_text='When unchecked, runs with this variable value will NOT appear on the main page, even if the parent category is enabled.', verbose_name='Appear on Main Page'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='rules',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='levels',
            name='rules',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='runs',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='variablevalues',
            name='rules',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Rules'),
        ),
    ]
