# Generated by Django 6.0.2 on 2026-02-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srl', '0017_variablevalues_appear_on_main'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['game', 'type'], name='idx_categories_game_type'),
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['appear_on_main'], name='idx_categories_main'),
        ),
        migrations.AddIndex(
            model_name='players',
            index=models.Index(fields=['name'], name='idx_players_name'),
        ),
        migrations.AddIndex(
            model_name='players',
            index=models.Index(fields=['nickname'], name='idx_players_nickname'),
        ),
        migrations.AddIndex(
            model_name='runplayers',
            index=models.Index(fields=['player', 'run'], name='idx_runplayers_player_run'),
        ),
        migrations.AddIndex(
            model_name='runs',
            index=models.Index(fields=['game', 'category', 'place'], name='idx_runs_game_cat_place'),
        ),
        migrations.AddIndex(
            model_name='runs',
            index=models.Index(fields=['game', 'level', 'place'], name='idx_runs_game_level_place'),
        ),
        migrations.AddIndex(
            model_name='runs',
            index=models.Index(fields=['place', 'obsolete', 'vid_status'], name='idx_runs_place_obs_status'),
        ),
        migrations.AddIndex(
            model_name='runs',
            index=models.Index(fields=['game', 'category', 'subcategory', 'level'], name='idx_runs_game_cat_sub_level'),
        ),
        migrations.AddIndex(
            model_name='runs',
            index=models.Index(fields=['-v_date'], name='idx_runs_vdate_desc'),
        ),
        migrations.AddIndex(
            model_name='runs',
            index=models.Index(fields=['runtype'], name='idx_runs_runtype'),
        ),
        migrations.AddIndex(
            model_name='variables',
            index=models.Index(fields=['game', 'cat'], name='idx_variables_game_cat'),
        ),
        migrations.AddIndex(
            model_name='variables',
            index=models.Index(fields=['game', 'scope'], name='idx_variables_game_scope'),
        ),
    ]
