# Generated by Django 6.0.2 on 2026-02-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0018_categories_idx_categories_game_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="order",
            field=models.IntegerField(
                default=0,
                verbose_name="Sort Order",
                help_text=(
                    "Controls display order. order=0 items sort alphabetically as a fallback. "
                    "Items with order>=1 sort first in ascending order."
                ),
            ),
        ),
        migrations.AddField(
            model_name="levels",
            name="order",
            field=models.IntegerField(
                default=0,
                verbose_name="Sort Order",
                help_text=(
                    "Controls display order. order=0 items sort alphabetically as a fallback. "
                    "Items with order>=1 sort first in ascending order."
                ),
            ),
        ),
    ]
