# Generated by Django 6.0.2 on 2026-02-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srl", "0019_categories_order_levels_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="variablevalues",
            name="order",
            field=models.IntegerField(
                default=0,
                verbose_name="Sort Order",
                help_text=(
                    "Controls display order within this variable's values. "
                    "order=0 items sort alphabetically as a fallback. "
                    "Items with order>=1 sort first in ascending order."
                ),
            ),
        ),
    ]
